### ISSUE TITLE
Ubuntu compilation failure due to missing <memory>

### ISSUE THREAD

**Issue by WenyinWei** [AnyarInc/Ascent#18]
- OS: Ubuntu 18.04
- Compiler Suite: GNU-8.4.0

Hi guys, I have been stuck in the compilation stage, encountering some trouble with the very latest compiler suite and CMake version. Maybe we can set some prerequisites in README, e.g. CMake 3.12 and gcc-8, to tell users what they need before using Ascent, as Ascent uses many fancy and modern C++ style codes.

Even equipped with the newest compiler, I still met the following failure, which told me I need to add `#include <memory>` in unit_test. Fortunately, everything goes well after I prepended it. Maybe we also need to add some automatic CI workflow check to ascent.

![image](https://user-images.githubusercontent.com/33152225/127084042-2defebbb-69b8-435b-b0a3-190cafa10393.png)

Compilation on Windows platform runs swiftly and comfortably, awesome ascent, thx!

**Comment by stephenberry** [comment]
Thanks for your feedback. I definitely want to add more CI. My team tests code on GCC, but I'm not sure the last version that is supported. I'll try to make the prerequisites more clear.
Sincerely,
Stephen

**Comment by stephenberry** [comment]
The issue of the missing `<memory>` include has been resolved in a recent commit. I still plan to add CI soon. Thanks for pointing out this error.
